name: todo_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  
  # State Managment
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  
  # Navigate
  auto_route: ^9.2.0

  # Animation
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.2
  fluttertoast: ^8.2.6
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.1
  flutter_native_splash: ^2.4.1

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.4

  # Core
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  flutter_localization: ^0.2.0
  shared_preferences: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.3.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12

flutter_launcher_icons:
  android: "white_app_icon"
  ios: false
  image_path: "assets/png/white_app_icon.png"
  min_sdk_android: 21 

  flutter_lints: ^3.0.0

  
flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        